import { existsSync } from "node:fs";
import { isAbsolute, join } from "node:path";
import type { Plugin } from "vite";
import type { ResolvedShironesPaths } from "./types.ts";

/**
 * Resolve bare specifiers that only exist inside the theme package.
 *
 * Under pnpm's strict `node_modules` layout, the theme's own dependencies are
 * not visible from the user's project root. Most imports are fine because
 * their importer lives inside the package, so Vite walks up from there — but
 * some are requested from contexts anchored at the project root:
 *
 *   - `virtual:astro:renderers`, generated by Astro, imports
 *     `@astrojs/svelte/server.js`
 *   - injected route entrypoints resolved before their importer is known
 *   - `astro:scripts/page.js`, the virtual module that carries the
 *     `@swup/astro` init script, imports `@swup/astro/serialise`,
 *     `@swup/astro/idle`, and the `@swup/astro/client/*` plugin modules
 *
 * Those fail with "failed to resolve import … from …".
 *
 * Rather than pushing a pile of implementation-detail packages onto the user's
 * dependency list, this plugin retries any failed bare specifier using a file
 * inside the package as the importer, which makes Vite search the package's
 * own `node_modules`. Vite does the resolving, so `exports` maps and ESM-only
 * packages behave exactly as they should.
 */
export function shironesFallbackResolver(paths: ResolvedShironesPaths): Plugin {
	// Any real path inside the package works as a resolution anchor: Vite walks
	// up from its directory looking for `node_modules`.
	const anchor = join(paths.packageRoot, "package.json");
	const rescued = new Map<string, string>();

	return {
		name: "shirones:fallback-resolver",
		// Runs after Vite's own resolver so we only see genuine failures.
		enforce: "post",

		async resolveId(source, importer, options) {
			// Only bare specifiers can miss because of the node_modules layout.
			if (/^[./]/.test(source)) return null;
			if (source.startsWith("\0")) return null;
			if (source.includes(":")) return null; // virtual:, astro:, node:, data:

			// Guard against re-entering through our own `this.resolve` calls.
			if (options?.custom?.["shirones:fallback"]) return null;
			const custom = { ...options?.custom, "shirones:fallback": true };

			const direct = await this.resolve(source, importer, {
				...options,
				skipSelf: true,
				custom,
			});
			// Resolvable as-is: stay out of the way.
			if (isGenuineResolution(direct)) return null;

			const fallback = await this.resolve(source, anchor, {
				...options,
				skipSelf: true,
				custom,
			});
			if (!isGenuineResolution(fallback)) return null;

			if (!rescued.has(source)) {
				rescued.set(source, fallback.id);
			}
			return fallback;
		},

		buildEnd() {
			if (rescued.size === 0) return;
			const names = [...rescued.keys()].sort().join(", ");
			this.info?.(`resolved from the theme package: ${names}`);
		},
	};
}

/** Minimal structural view of what `this.resolve()` hands back. */
type Resolution = {
	id: string;
	external?: boolean | string;
	meta?: Record<string, unknown>;
};

/**
 * Decide whether a resolution result is real or a dev-server stand-in.
 *
 * Truthiness is not enough: the dev server answers *unresolvable* bare
 * specifiers with truthy results instead of `null`, in at least two shapes.
 *
 *   1. Vite 8's builtin resolver, asked to resolve a bare specifier whose
 *      importer is a virtual module (like `astro:scripts/page.js`), maps it
 *      onto a root-relative pseudo path — `<root>/@swup/astro/serialise` —
 *      that exists on no disk. Believing that result makes this plugin stand
 *      down while `vite:import-analysis` still fails the import.
 *   2. Vite's dev alias plumbing can return a
 *      `{ meta: { "vite:alias": { noResolved: true } } }` sentinel that
 *      `vite:import-analysis` itself treats as a failure.
 *
 * Production builds never produce either shape — the bundler returns a real
 * `null` — which is why the same plugin worked there. A genuine filesystem
 * resolution must point at a file that exists; virtual modules
 * (`\0`-prefixed), externals, and non-path ids are genuine by definition.
 */
export function isGenuineResolution(
	resolved: Resolution | null | undefined,
): resolved is Resolution {
	if (!resolved) return false;
	if (resolved.external) return true;
	const aliasMeta = resolved.meta?.["vite:alias"] as
		| { noResolved?: boolean }
		| undefined;
	if (aliasMeta?.noResolved) return false;
	const { id } = resolved;
	if (typeof id !== "string") return false;
	if (id.startsWith("\0")) return true; // virtual module id
	const file = id.split("?")[0].split("#")[0];
	if (!isAbsolute(file)) return true; // bare/external-ish id: nothing to stat
	return existsSync(file);
}
